import AppContext from './TimerContext.js';
import './index.css';
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import CssBaseline from '@mui/material/CssBaseline';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
	  <head>
	  <link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
/>

	  <meta name="viewport" content="initial-scale=1, width=device-width" />
	  </head>
      	  <body className={inter.className}>
	  <AppContext>
	  {children}
	  </AppContext>
	  </body>
    </html>
  )
}
